### ISSUE TITLE
missed files for install

### ISSUE THREAD

**Issue by Marijsoft** [Codrax/CodrutsVisualLibrary#1]
error install components missed  files Cod.VarHelpers and Cod.Graphics

**Comment by Codrax** [comment]
The Cod unit dependencies have been added. You can now find them in the Dependencies folder

**Comment by kazuser** [comment]
@Codrax 

![image](https://github.com/Codrax/CodrutsVisualLibrary/assets/3335273/767db250-5490-4563-9ea2-6957e4035dd8)

What about "PngComponents"?

Which one?

![image](https://github.com/Codrax/CodrutsVisualLibrary/assets/3335273/6bb7408b-bb5a-4361-82f0-98afb8534ea8)

**Comment by Codrax** [comment]
The one by Turbo Pack. You can also download it from the IDE using the GetIT Package Manager.
https://getitnow.embarcadero.com/PNGComponents-1.4-Sydney/
