### ISSUE TITLE
D10.2.3

### ISSUE THREAD

**Issue by limelect** [Codrax/CodrutsVisualLibrary#3]
It will be nice to use your library with D10.2.3

**Comment by Codrax** [comment]
Does It have any issues on delphi 10? I haven't tested that version since a year or so.
Please tell me exactly what issues you are encountering

**Comment by limelect** [comment]
Yes lot to begin with var I have to move it this is easy
but Trect and    R: TRect;  //TGPRectF;// on DrawText(
and 
//        const
        R:= TRect( MakeRect(Single(Rectangle.Left), Rectangle.Top, Rectangle.Width, Rectangle.Height));
        G.DrawString(PChar(Text), -1, Font, R, Format, Brush );

G.DrawString
well maybe there are more
You should try to get 10+ to compile  as I am sure there are more problems

**Comment by Codrax** [comment]
If I have some free time on my hands, I'll take a look at the issue, but I'm not sure I can even get my hands on a delphi 10.2 license.

**Comment by limelect** [comment]
well, your components are for a small community then.
goog luck
